### ISSUE TITLE
[docs] Use new demos for the visual tests

### ISSUE THREAD

**Issue by vladmoroz** [mui/base-ui#1003]
@mnajdova @michaldudak is this an alpha thing?

For context, I have already seen regressions in the new demos due to recent changes, and plan to remove the `data` folder altogether, recreating as many advanced demos as possible

**Comment by colmtuite** [comment]
I don't think demos and tests should be connected. Testing should be independent of presentation.

**Comment by mj12albert** [comment]
@vladmoroz You are referring to the Argos check in our CI?

**Comment by vladmoroz** [comment]
> @vladmoroz You are referring to the Argos check in our CI?

Yep

> I don't think demos and tests should be connected. Testing should be independent of presentation.

There are visual tests that already are though. Every old demo is visually diffed as part of the CI on PRs.

**Comment by michaldudak** [comment]
It's expected that Argos will report issues often now that we're recreating the demos. Once the demos are stable, Argos helps us catch bugs that can result in small changes in presentation.

**Comment by vladmoroz** [comment]
Right, @michaldudak, so what I'm saying is that I want Argos to check against the new demos since they aren't hooked up yet

**Comment by mj12albert** [comment]
Happy to take this one 👋
