### ISSUE TITLE
[Field] Base UI components link to hidden input `id`

### ISSUE THREAD

**Issue by atomiks** [mui/base-ui#1051]
In Checkbox, Switch, Select, the `id` points to the hidden `<input>` which causes a violation when clicking `Field.Label` and focus is not placed on the rendered control/button

**Search keywords**:

**Comment by michaldudak** [comment]
Could you provide a simple repro? I tried https://codesandbox.io/p/sandbox/jolly-violet-jy2zx3?file=%2Fsrc%2FDemo.tsx%3A12%2C36 but don't see any violations.

**Comment by atomiks** [comment]
It happens in that sandbox

<img width="498" alt="Screenshot 2024-12-15 at 4 30 57 pm" src="https://github.com/user-attachments/assets/48d95d7b-56c6-41b8-ad14-6b0493ad88d4" />

**Comment by michaldudak** [comment]
It does now indeed. Strange as I was looking at it before and could trigger the warning...
