### ISSUE TITLE
[Select] The `onValueChange` and `onOpenChange` typing are not correct on the doc

### ISSUE THREAD

**Issue by flaviendelangle** [mui/base-ui#1061]
# Docs feedback

## How can we improve Base UI documentation?

Whenever possible, the props should have a detailed type in the API section of the doc, not `function`.
Looking at the code I can't tell why only the Select one does not work :shrug: 

The Select API doc:

![image](https://github.com/user-attachments/assets/e8fd2fb5-585d-4be4-b44c-686d79ba4bb6)

The Menu API doc:  (same for Dialog and the Popover)

![image](https://github.com/user-attachments/assets/384780e8-b2f7-4136-93ab-2fa30de49f01)

I did not check if they were other occurences of `function` in the doc 

**Search keywords**:

**Comment by mj12albert** [comment]
So `function` is just generated by `pnpm proptypes`, but we now have this `overrides` directory with some json ([Menu for example](https://github.com/mui/base-ui/blob/master/docs/reference/overrides/menu-root.json)) that overrides the output of that for the props table in the docs site, so the one for Select was missing!
