### ISSUE TITLE
[Menu, Select] Trigger `label` prop appears to be unused

### ISSUE THREAD

**Issue by vladmoroz** [mui/base-ui#1072]
Not sure what the original purpose of the prop was, but it's not used in any way. Should we remove it?

https://github.com/mui/base-ui/blob/master/packages/react/src/select/trigger/SelectTrigger.tsx
https://github.com/mui/base-ui/blob/master/packages/react/src/menu/trigger/MenuTrigger.tsx

**Search keywords**:

**Comment by michaldudak** [comment]
It seems that the only purpose of it was to prevent it from being applied to the rendered `<button />`. I don't remember why, though.
