### ISSUE TITLE
[useButton] Remove `event.defaultMuiPrevented` and `MuiCancellableEvent`

### ISSUE THREAD

**Issue by vladmoroz** [mui/base-ui#1106]
There is a couple references to `event.defaultMuiPrevented` in the codebase. Should these be using `event.defaultPrevented` like others?

**Comment by mj12albert** [comment]
This was the old way to prevent our (internal) handlers from running without affecting custom event handlers, the new way is with a `event.preventBaseUIHandler` method: https://github.com/mui/base-ui/blob/master/packages/react/src/utils/mergeReactProps.ts#L6-L7

I see the old references are all in useButton, some of that code may be unused now and could be cleaned up a bit

**Comment by mj12albert** [comment]
Turns out `MenuItem` was the last thing depending on this: https://github.com/mui/base-ui/pull/542/files#r1721346832
