### ISSUE TITLE
[popups] Clicking outside of nested popups closes all of them

### ISSUE THREAD

**Issue by michaldudak** [mui/base-ui#1107]
Whenever there are nested popups open, such as a Menu or a Select in a Dialog, clicking outside of them closes all of them. The correct behavior would be to close just the topmost one (as nested Dialogs currently behave).

**Comment by mj12albert** [comment]
I'll work on this one

**Comment by mj12albert** [comment]
It's fixed in https://deploy-preview-1161--base-ui.netlify.app/experiments/popups-in-popups
