### ISSUE TITLE
[dialog] Nested alert dialogs aren't recognised as nested dialogs and vice versa

### ISSUE THREAD

**Issue by vladmoroz** [mui/base-ui#1165]
`[data-has-nested-dialogs]` attribute isn't applied when a dialog composes an alert dialog:
https://codesandbox.io/p/sandbox/7yw3n3

When fixed, please update the confirmation dialog demo (https://github.com/mui/base-ui/pull/1164) to use an alert dialog within.

**Comment by atomiks** [comment]
This is one area where a simple prop on `Dialog` could've worked better for alert dialogs. Maybe we should reconsider?

**Comment by mnajdova** [comment]
> This is one area where a simple prop on Dialog could've worked better for alert dialogs. Maybe we should reconsider?

I had the same thought, if these two were different variants of the same component this never would have happened. Last time we discussed this was that we don't want to spend more time on this now (I mean on refactorign the Dialog component to support both of these two scenarios).
