### ISSUE TITLE
[docs] Make navigation items clickable in the full width of the navigation

### ISSUE THREAD

**Issue by Studio384** [mui/base-ui#1178]
# Docs feedback

## How can we improve Base UI documentation?

Currently, only the text and a small padding on either side of the text in the navigation is clickable. The "active page" indication however takes the full width and thus implies that the entire width of sidebar is interactive.

I've repeatedly found myself clicking on the right side of a page item where there is no link, it would be great if the full width of the sidebar is used.

**Comment by atomiks** [comment]
Fix is now live
