### ISSUE TITLE
[Select] Integrate with FormControlUnstyled

### ISSUE THREAD

**Issue by michaldudak** [mui/base-ui#12]
Make SelectUnstyled aware of the FormControlUnstyled context, similarly to how Material UI's Select interacts with FormControl.

**Comment by ivan-ngchakming** [comment]
Hi, I'd like to work on this.

From my understanding, add the `useFormControlUnstyled` hook in `<SelectUnstyled>`, so `<SelectUnstyled>` can be aware of the following properties: `disabled`, `error`, `focused`, `required`?

I suppose some demos should be added showing how to use `<FormControlUnstyled>` together with `<SelectUnstyled>`, I am thinking I can add them in a separate PR.

**Comment by michaldudak** [comment]
Hi, could you please hold it off for a bit? I have some changes to FormControlUnstyled in progress. I hope to create a PR tomorrow at most.

**Comment by michaldudak** [comment]
@ivan-ngchakming Here's the PR with the changes I mentioned: mui/material-ui#32134

Once it's merged in, you may work on this issue.

**Comment by michaldudak** [comment]
We replaced FormControlUnstyled with Form and Field components. The Select will support them out of the box.
