### ISSUE TITLE
[docs] Missing line on Composition page in "Composing multiple components"

### ISSUE THREAD

**Issue by DanielGibbsNZ** [mui/base-ui#1211]
# Docs feedback

## How can we improve Base UI documentation?

In the "Composing multiple components" section on the Composition page, there is a missing line that is not showing in the code example. The line is `<Menu.Item render={<a href="base-ui.com" />}>` (source [here](https://github.com/mui/base-ui/blob/master/docs/src/app/(public)/(content)/react/handbook/composition/page.mdx?plain=1#L69)). Perhaps the `prettier-ignore` comment on the line above is causing it to be skipped somehow?

**Comment by atomiks** [comment]
It's not just that line it looks like. The entire page's code blocks have issues seemingly due to the `prettier-ignore` as you point out!

It appears to be a regression from #1187
