### ISSUE TITLE
[Slider] Support markers/indicators along the track

### ISSUE THREAD

**Issue by thevipinmishra** [mui/base-ui#1229]
# Feature request

## Summary

Sometimes we do want to indicate or highlight some predetermined values that can be chosen along the track. In the native `<input type='range' />`, we can do it by adding a <datalist /> and linking it with the id.

```html
<input type="range" min="-100" max="100" value="0" step="10" name="power" list="powers">
<datalist id="powers">
   <option value="0">
   <option value="-30">
   <option value="30">
   <option value="++50">
</datalist>
```

The Slider should also snap to the closest marker/indicator.

## Examples in other libraries

MUI - https://mui.com/material-ui/react-slider/#discrete-sliders

Mantine - https://mantine.dev/core/slider/#marks

ARK UI - https://ark-ui.com/react/docs/components/slider#adding-marks

Chakra UI - https://www.chakra-ui.com/docs/components/slider#marks

**Comment by aarongarciah** [comment]
@thevipinmishra I just saw https://github.com/mui/base-ui/issues/462 already exists. I've added the additional info you provided on this issue but I'll go ahead and close this one.
