### ISSUE TITLE
[TextareaAutosize] Glitchy resizing

### ISSUE THREAD

**Issue by cherniavskii** [mui/base-ui#160]
### Steps to reproduce

Link to live example: https://stackblitz.com/edit/react-ktw8pj?file=Demo.tsx

Steps:
1. Resize textarea vertically

### Current behavior

Resizing is glitchy

https://github.com/mui/base-ui/assets/13808724/e32d7c83-463e-4a92-8cba-6db1c4dc0f93

### Expected behavior

Resizing should be smooth

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: text area resize glitch

**Comment by nktnet1** [comment]
The same issue with from material-ui was recently moved to base-ui here: https://github.com/mui/base-ui/issues/168

**Comment by ZeeshanTamboli** [comment]
Created a PR to fix it - #189.

**Comment by colmtuite** [comment]
Auto-sizing can be handled natively these days with `field-sizing`. So we're going to deprecate this component soon.

**Comment by Octobr26** [comment]
Hi,

After testing the AutoResize component across different platforms, I found that its behavior varies slightly depending on the OS:

MacOS: The component is glitchy with inconsistent behavior during resizing.
Windows 10: same as MacOS.
Windows 11: It works well on this platform.

Given that it functions across platforms, albeit with minor glitches on some, it remains usable for end users depending on the platform they're on
