### ISSUE TITLE
[TextAreaAutoresize] null value exception

### ISSUE THREAD

**Issue by alankent** [mui/base-ui#164]
### Steps to reproduce 🕹

Link to live example:
<img width="554" alt="image" src="https://github.com/mui/material-ui/assets/5702163/ecbc2794-c2fa-4401-adf2-2e9be532bdba">

I have not managed to repeat in a smaller example app, but using the debugger it is pretty clear that resizing the window with different breakpoints is causing `getComputedStyle(input)` to fail as `input` is null. The lines are:
```
    const input = inputRef.current;
    const containerWindow = ownerWindow(input);
    const computedStyle = containerWindow.getComputedStyle(input);
```

The stack trace is:
```
TextareaAutosize.js:67 Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at eval (TextareaAutosize.js:67:1)
    at syncHeightWithFlushSync (TextareaAutosize.js:143:1)
    at handleResize (TextareaAutosize.js:159:1)
    at later (debounce.js:8:1)
```
In the debugger, printing out `input` it says `null`. So the `parameter 1 is not of type Element` is because null is being passed in.

Steps:
1. Build a complex app with breakpoints to reflow the screen, make things appear and disappear etc.
2. Resize the window multiple times across the various breakpoint edges, with a `<Textarea...>` on the page (inside a closed `<Modal>`).

Note: The only `<Textarea...>` component I have is in a closed modal dialog. So it is not visible on the screen. If I comment out the `<Textarea...>` the exception no longer comes up. My component markup is pretty straightforward.:w

```
<Textarea
    placeholder="Enter cast member description..."
    value={description}
    onChange={(e) => setDescription(e.target.value)}
    minRows={3}
/>
```

### Current behavior 😯

I get exceptions in the console and an error message on the screen when resizing the window.
<img width="482" alt="image" src="https://github.com/mui/material-ui/assets/5702163/23124166-41c0-4bd0-82b6-988c1c227aa8">

### Expected behavior 🤔

There should not be an exception.

### Context 🔦

I am trying to resize the window, with complex breakpoints, with a `<Textarea...>` in a closed modal dialog box.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
I am using Chrome.
$ npx @mui/envinfo
npm WARN exec The following package was not found and will be installed: @mui/envinfo@2.0.13

  System:
    OS: Windows 11 10.0.22621
  Binaries:
    Node: 20.4.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 9.7.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Chromium (119.0.2151.72)
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.1
    @emotion/styled: ^11.11.0 => 11.11.0
    @mui/base:  5.0.0-beta.24
    @mui/core-downloads-tracker:  5.14.18
    @mui/icons-material: ^5.13.7 => 5.14.18
    @mui/joy: ^5.0.0-beta.15 => 5.0.0-beta.15
    @mui/lab: ^5.0.0-alpha.135 => 5.0.0-alpha.153
    @mui/material: ^5.13.7 => 5.14.18
    @mui/private-theming:  5.14.18
    @mui/styled-engine:  5.14.18
    @mui/system:  5.14.18
    @mui/types:  7.2.9
    @mui/utils:  5.14.18
    @types/react:  18.2.37
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
```
</details>

**Search keywords**:

**Comment by mj12albert** [comment]
Looks very similar to https://github.com/mui/material-ui/issues/32640 🤔

**Comment by gitstart** [comment]
@mj12albert We would like to work on this issue.

**Comment by colmtuite** [comment]
Auto-sizing can be handled natively these days with `field-sizing`. So we're going to deprecate this component soon.

[Demo](https://jsfiddle.net/as0r6evg/)
