### ISSUE TITLE
[number field] Implement NumberField with new API

### ISSUE THREAD

**Issue by atomiks** [mui/base-ui#185]
### Summary

Replaces the `NumberInput` component.

This is the place to gather ideas, measure interest and discuss the API and implementation details of the `NumberField` component and hook.

## Anatomy

```js
<NumberField>
  <NumberField.Group>
    <NumberField.Input />
    <NumberField.Decrement />
    <NumberField.Increment />
    <NumberField.Scrubber />
  </NumberField.Group>
</NumberField>
```

### **Root**

Rendered element: `div`

<table> <thead> <tr> <th>prop</th> <th>type</th> <th>default</th> <th>description</th> </tr> </thead> <tbody> <tr> <td>defaultValue</td> <td>number</td> <td></td> <td></td> </tr> <tr> <td>id</td> <td></td> <td></td> <td></td> </tr> <tr> <td>min</td> <td>number</td> <td></td> <td></td> </tr> <tr> <td>max</td> <td>number</td> <td></td> <td></td> </tr> <tr> <td>step</td> <td>number</td> <td>1</td> <td></td> </tr> <tr> <td>largeStep</td> <td>number</td> <td>10</td> <td></td> </tr> <tr> <td>required</td> <td>boolean</td> <td></td> <td></td> </tr> <tr> <td>disabled</td> <td>boolean</td> <td></td> <td></td> </tr> <tr> <td>invalid</td> <td>boolean</td> <td></td> <td></td> </tr> <tr> <td>autoFocus</td> <td>boolean</td> <td></td> <td></td> </tr> <tr> <td>children</td> <td></td> <td></td> <td></td> </tr> <tr> <td>readOnly</td> <td>boolean</td> <td></td> <td></td> </tr> <tr> <td>name</td> <td>string</td> <td></td> <td></td> </tr> <tr> <td>value</td> <td>number</td> <td></td> <td></td> </tr> <tr> <td>onChange</td> <td>function</td> <td></td> <td></td> </tr> <tr> <td>format</td> <td>Intl.NumberFormatOptions</td> <td></td> <td></td> </tr> </tbody> </table>

Other props (unnamed):

- Ability to scrub the input with the `wheel`
- Locale for `format`

### **Group**

Rendered element: `div`

All `div` attrs.

### **Input**

Rendered element: `<input type="text" />`

All `input` attrs.

### **Decrement**

Rendered element: `button` 

All `button` attrs.

### **Increment**

Rendered element: `button` 

All `button` attrs.

### **Scrubber**

Rendered element: `span` 

All `span` attrs.

## Benchmarks

- https://react-spectrum.adobe.com/react-aria/NumberField.html
- https://chakra-ui.com/docs/components/number-input

**Search keywords**: number field, number input

**Comment by oliviertassinari** [comment]
> Benchmarks

The benchmark list we maintain on Notion: https://www.notion.so/mui-org/core-Input-Number-component-364825a7bec94381809ac11ff05b4cc0 for this one.
