### ISSUE TITLE
[number field] Disable focus on mobile

### ISSUE THREAD

**Issue by oliviertassinari** [mui/base-ui#224]
### Steps to reproduce

https://mui.com/base-ui/react-number-input/#customization

https://github.com/mui/base-ui/assets/3165635/ee32167a-b35c-4278-8b07-631a5edadff3

### Current behavior

The input is focused on mobile, so the virtual keyboard triggers

### Expected behavior

No input focus on mobile when using the control. 

### Context

See https://www.notion.so/mui-org/core-Input-Number-component-364825a7bec94381809ac11ff05b4cc0. For eample https://react-spectrum.adobe.com/blog/how-we-internationalized-our-numberfield.html looks correct to me. Focus on desktop, no focus on mobile.

### Your environment

@mui/base@5.0.0-beta.36

**Search keywords**: focus

**Comment by colmtuite** [comment]
Closing this as it's not an issue on our new implementation which should be merged end of next week.

**Comment by oliviertassinari** [comment]
@colmtuite I updated the PR that fixes this bug (#186) to include "Closes #224", this is for clarity, and to automatically close the issue once merged. We normally close issues only once HEAD is fixed (`master` branch today). This is because a PR might get abandoned, split in chunks, etc. It's also a convention between open source projects.
