### ISSUE TITLE
[RadioGroup] Implement RadioGroup

### ISSUE THREAD

**Issue by michaldudak** [mui/base-ui#26]
This is the place to gather ideas, measure interest and discuss the API and implementation details of the radio button and radio group components and hooks.

See https://github.com/mui/base-ui/issues/10 for the umbrella issue to track progress on Base UI and https://github.com/mui/material-ui/issues/6218 for the problem this project solve.

**Comment by andrejsshell** [comment]
I'd like to take on this issue 🙌🏼

**Comment by michaldudak** [comment]
We haven't fleshed out the design details of it, so it's not ready to take just yet.
