### ISSUE TITLE
[useAutocomplete] Add support for `groupedOptions` to always be returned regardless of focus

### ISSUE THREAD

**Issue by martin-slalom** [mui/base-ui#269]
### Summary

I have a need to build my own autocomplete that renders the groupedOptions/list options and the input in a single popover. The only issue I'm running into with `useAutocomplete` to build out this component out is that the `groupedOptions` is changed to an empty array when the input is no longer focused. My proposal would be to add a prop to the useAutocomplete that would override this functionality to allow the list to be rendered regardless of the input being focused. This would give the developer more freedom to build out the dropdown list.

### Examples

Example use case, I need to create an account selector that shows the Currently selected account but when you click the name it opens a Popover with a search input and the list of accounts. As the user types it filters and acts just like the autocomplete where the user can select a value and it will then navigate them. 

I've thrown together, a very rough, [example]( https://codesandbox.io/p/sandbox/reverent-haze-5lvs8l?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clu1ss12x00073b6gqyze7ztc%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clu1ss12x00033b6g53oikx3l%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clu1ss12x00043b6gs0sewbly%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clu1ss12x00063b6gvianhs1p%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clu1ss12x00033b6g53oikx3l%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu1ss12x00023b6g21g7z3xs%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FDemo.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A45%252C%2522startColumn%2522%253A21%252C%2522endLineNumber%2522%253A45%252C%2522endColumn%2522%253A21%257D%255D%257D%255D%252C%2522id%2522%253A%2522clu1ss12x00033b6g53oikx3l%2522%252C%2522activeTabId%2522%253A%2522clu1ss12x00023b6g21g7z3xs%2522%257D%252C%2522clu1ss12x00063b6gvianhs1p%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu1ss12x00053b6g0gucjd0y%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clu1ss12x00063b6gvianhs1p%2522%252C%2522activeTabId%2522%253A%2522clu1ss12x00053b6g0gucjd0y%2522%257D%252C%2522clu1ss12x00043b6gs0sewbly%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clu1ss12x00043b6gs0sewbly%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) of this. You'll notice that when you click "The Godfather" in the blue bar a popover opens and the list reads "no results". This is because the input isn't focused, then when the input is focused the list appears. We can set `autoFocus` on the input and set `openOnFocus` on the useAutocomplete however, when the user selects an option from the list the focus is then changed to that item, away from the input and thus the list closes (reverting to "no results").

I propose an "override" prop on the `useAutocomplete` component to give the developer freedom to receive the list without worrying about the focus state of the input.

```diff
  const popupOpen = open && !readOnly;

-  const filteredOptions = popupOpen
+  const filteredOptions = ignoreFocus || popupOpen
    ? filterOptions(
        options.filter((option) => {
          if (
            filterSelectedOptions &&
            (multiple ? value : [value]).some(
              (value2) => value2 !== null && isOptionEqualToValue(option, value2),
            )
          ) {
            return false;
          }
          return true;
        }),
        // we use the empty string to manipulate `filterOptions` to not filter any options
        // i.e. the filter predicate always returns true
        {
          inputValue: inputValueIsSelectedValue && inputPristine ? '' : inputValue,
          getOptionLabel,
        },
      )
    : [];

```

**Search keywords**: useAutocomplete

**Comment by ZeeshanTamboli** [comment]
@martin-slalom I'm having trouble understanding your issue. Your CodeSandbox example, although somewhat unclear, doesn't seem to be behaving as you described. If the list isn't being shown and the input isn't focused, why do you require `groupedOptions`? Displaying "No results" should be incorporated into the options list itself rather than serving as a placeholder for the input. Additionally, you should render the listbox only when there are `groupedOptions` available.

**Comment by martin-slalom** [comment]
@ZeeshanTamboli 
My apologies, I figured out the issue I've updated the [example](https://codesandbox.io/p/sandbox/reverent-haze-5lvs8l?file=%2Fsrc%2FDemo.tsx%3A67%2C1).  But the point I was trying to demonstrate in the demo is that for my use case the list should be shown when the popover is opened regardless if the user has focused the input or not. The only way to get the list to show up is if the input is focused, as soon as it's unfocused it goes away. 

For a "traditional" autocomplete I 100% agree with you that the listbox should only be rendered when `groupedOptions` are available (aka the input is focused). However for my use case it's not a traditional autocomplete the input and `groupedOptions` need to be rendered together at the same time in say a popover, card, dialog, etc. This is not possible with the current state of the `useAutocomplete` hook only because of the "open" logic that reverts the `filteredList` (aka `groupedOptions`) back to `[]` once focus state isn't on the input. This including using tab to select from filtered options since the focus is now on the menu items.

 My feature request is to add a prop that could be toggled on to give the developer the ability to overwrite that resetting to "[]" so that they may utilize the hook in non-traditional ways.

![2024-03-29 09 59 21](https://github.com/mui/material-ui/assets/121053732/f364fd85-c520-4415-94f4-5a3906bab2ff)

**Comment by ZeeshanTamboli** [comment]
If you're not building an autocomplete feature, it's best not to utilize the `useAutocomplete` hook. Instead, consider creating your own custom hook tailored to your specific requirements. Could you try focusing the input programmatically when the popup is opened?

I don't believe we'll add a prop for this. It doesn't seem necessary to me. I'm closing this issue.

**Comment by martin-slalom** [comment]
So the thing is @ZeeshanTamboli my feature _is_ functionally an autocomplete in every regard. It's just not visually a "traditional autocomplete" where the dropdown is triggered by focusing an input, rather the input and dropdown live together in a popover that's triggered by the clicking another element. It has the same need for everything that a traditional autocomplete would would have EXCEPT the clearing of the dropdown list once the input loses focus. I'm confused how that is not shown via my example, could you please explain how the component in the codesandbox is not an autocomplete?

Additionally, focusing the input programmatically when the popup is opened does work _until_ you use the "tab" functionality to select an item from the list since at that point the input would loose focus for that of the list item button, as you can see in the example.

![2024-04-01 09 14 25](https://github.com/mui/material-ui/assets/121053732/23e1f3a4-ddad-4c5c-97c0-5363f01d49b2)

**Comment by ZeeshanTamboli** [comment]
In the autocomplete, we use the [combobox W3 ARIA pattern](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/). According to this pattern, the popover is hidden by default and requires a trigger to be opened.

**Comment by martin-slalom** [comment]
> In the autocomplete, we use the [combobox W3 ARIA pattern](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/). According to this pattern, the popover is hidden by default and requires a trigger to be opened.

I feel like my example/use case still follows that pattern as well, the popover/list is hidden by default and exposed via a trigger as well.  It's just that trigger in this case isn't an input it's a div. The user can filter the list via typing in the input, "hover" over options via arrow/tab keys, and selecting one by clicking or pressing enter. Other features like list grouping can also be used. 

Maybe there's some confusion, especially since the tag is "component:Autocomplete", I'm not suggesting **_any_** changes to the Mui Autocomplete component. I'm merely suggesting an enhancement to the `useAutocomplete` hook. In my use case, yes a bit of a nontraditional pattern but, the functionality the hook provides does 99.5% of exactly what is needed, aside from the whole resetting of the `groupedOptions` when the input loses focus. 

My requested change would have no effect at all on the Mui Autocomplete at all. It would only add flexibility/functionality to `useAutocomplete` hook. It wouldn't even need to be exposed via Autocomplete's props (and probably shouldn't) and only be available for `useAutocomplete`.

**Comment by ZeeshanTamboli** [comment]
Both Material UI's Autocomplete and Joy UI's Autocomplete utilize the `useAutocomplete` internally, so this change could impact them.

> I feel like my example/use case still follows that pattern as well, the popover/list is hidden by default and exposed via a trigger as well. It's just that trigger in this case isn't an input it's a div.

Okay, I noticed the following statement in the ARIA docs as well: `It is displayed when the Down Arrow key is pressed or the Open button is activated.` Considering that a button trigger can open the list, I'll go ahead and open the issue. Feel free to propose a solution by creating a PR, but please make sure it doesn't impact the Material UI and Joy UI Autocompletes.

**Comment by ZeeshanTamboli** [comment]
Additionally, please keep in mind that the `useAutocomplete` functionality resides in Base UI within this repository (Core repo). However, we're planning to remove it from here. We're actively developing Base UI in a separate repository - https://github.com/mui/base-ui, so any changes must also be applied there. I'm also transferring this issue to Base UI repo.

**Comment by martin-slalom** [comment]
So should I open a PR against the Base-UI repo as well as Material-ui repo?

**Comment by ZeeshanTamboli** [comment]
> So should I open a PR against the Base-UI repo as well as Material-ui repo?

You can open it only in the Base UI repo. Version 1 of Base UI is coming soon, and the Base UI-related code will be removed from the Material UI repo.

**Comment by oliviertassinari** [comment]
I think I got clarity in https://github.com/mui/base-ui/pull/374#issuecomment-2129838724. The problem seems to be that blurring the input resets the input value. It sounds like a customization question, the `value` and `inputValue` states are controllable for use cases like this one. Or even better, why not use the `clearOnBlur` prop.

I think we can close this issue.

```diff
  } = useAutocomplete({
    ...props,
+   clearOnBlur: false,
+   open: true,
```

work for me https://codesandbox.io/p/sandbox/magical-torvalds-6tz24s?file=%2Fsrc%2FDemo.tsx%3A55%2C1-58%2C16

Same on https://mui.com/material-ui/react-autocomplete/#githubs-picker

https://github.com/mui/base-ui/assets/3165635/91e34c08-bf8d-4318-bcc1-148097a4a90a

thought IMHO it's better UX without `clearOnBlur`.

**Comment by martin-slalom** [comment]
Ahh I see, so it's the `open` prop that I was missing and provides the magic in the github "clone" example. I believe when I tried it was was trying to tie it to the open state of the popover but because that gets set to null _BEFORE_  the popover closed it was giving me an unintended result, the "no results" text.  I agree without `clearOnBlue` is much better from a UX POV.

I'll play around with hard coding it to `true`, I believe this can be closed, thank you for the clarification.
