### ISSUE TITLE
[Modal, FocusTrap] Playwright E2E tests incorrectly thinking elements are hidden

### ISSUE THREAD

**Issue by DurchblickerFabian** [mui/base-ui#318]
### Steps to reproduce

Link to live example: *Found no way to add playwright to Stackblitz or CodeSandbox*

Steps:
1. Create an empty page with a button/checkbox/...
2. Create a Modal with `disableEnforceFocus`, `hideBackdrop` and `disableScrollLock` set to `true`. Use case would be for example to position it on the bottom of the page, like a banner while still retaining full page interaction.
3. When you try to find all buttons on the page with `getByRole`, only buttons in the Modal will be found (-> the initially created button in the body is not found). Only when applying the option `includeHidden`, it will be found.

### Current behavior

I suspect that the focus trap lets Playwright think that all buttons/checkboxes/... outside of the Modal are not interactable/hidden (?) - but even when disabling enforce focus, it does not fix the problem. This issue only appears while the Modal is open, even when unstyled. It does not overlap with anything. Sadly, the focus trap inside the modal cannot be disabled/removed completely so it's hard to test if this would resolve the issue.

This seems to only affect E2E tests (at least with Playwright) and not normal page interaction.

Furthermore during playing around trying to fix it, I found out that the `ESC` handler is pretty unreliable when working with this kind of setup - it only works (as probably intended) while the Modal is focused. Could this be an additional option to optionally scope this to the whole document?

### Expected behavior

All buttons/checkboxes/... not in a Modal should still be "visible"/interactable (in terms of E2E tests) when no backdrop is used and focus is not enforced.

### Context

Since it's generally recommended to use `getByRole` in Playwright E2E tests instead of getting elements by their test id / label / etc. because of visibility checks and stuff (more "human" interaction), I would like to use it to find a button/checkbox/... while a Modal banner is open on the page. Normally interacting with the page works and it also works when enabling the `includeHidden` option, but this could then result in a successful test even if said button/checkbox is _really_ obstructed by something and thus not visible/interactable.

### Your environment

Used browser: Chromium 124.0.6367.29 (playwright build v1112) in Playwright
<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 14.4.1
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 123.0.6312.123
    Edge: Not Found
    Safari: 17.4.1
  npmPackages:
    @mui/base: 5.0.0-beta.36 => 5.0.0-beta.36 
    @mui/types:  7.2.14 
    @mui/utils:  5.15.14 
    @types/react: 18.2.57 => 18.2.57 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: 5.3.3 => 5.3.3
```
</details>

**Search keywords**: playwright, e2e, tests, testing, disableEnforceFocus, hideBackdrop

**Comment by michaldudak** [comment]
Modal elements, by definition, do not allow users to interact with other elements on a page. Playwright acts as a user (using assistive technologies), so it can't interact with elements that are not available for a real user.
