### ISSUE TITLE
[Select] Using keyboard Tab while Select is open does not move focus to the next field

### ISSUE THREAD

**Issue by rh-meowsa** [mui/base-ui#328]
### Steps to reproduce

Link to live example: https://mui.com/base-ui/react-select/

Steps:
1. Create a Select and also another field like an Input and or Button after the Select component
2. Pop open the Select dropdown
3. Hit keyboard Tab

### Current behavior

Focus goes to the browser's address bar

### Expected behavior

Focus goes to the next focusable item after the Select

### Context

a11y support for forms

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

  System:
    OS: macOS 14.4.1
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
    pnpm: 8.6.11 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 123.0.6312.124
    Edge: Not Found
    Safari: 17.4.1
  npmPackages:
    @mui/base: 5.0.0-beta.37 => 5.0.0-beta.37
    @types/react: 18.2.42 => 18.2.42
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0

  **Using Chrome 123.0.6312.124**
</details>

**Search keywords**: Keyboard, tab, Select

**Search keywords**:

**Comment by michaldudak** [comment]
Thanks for reporting this. It's not a desired behavior.
We are currently redesigning Base UI components (with a different customization API), and we should tackle the Select around June (see https://github.com/orgs/mui/projects/1/views/13). We'll work on fixing this then.
