### ISSUE TITLE
useNumberField and NumberField can not be imported (probably not exported from lib)

### ISSUE THREAD

**Issue by pav-stastny** [mui/base-ui#399]
### Steps to reproduce

Link to live example: (required)

Steps:
1. Go to docs: https://base-ui.netlify.app/base-ui/react-number-field/
2. Open stackblitz or codesandbox (https://codesandbox.io/p/sandbox/nice-williamson-6kk3lc?file=%2Fsrc%2FDemo.tsx)
3. It does not work 

### Current behavior

useNumberField  can not be imported

### Expected behavior

useNumberField can be imported

**Search keywords**: useNumberField NumberField

**Comment by atomiks** [comment]
Thanks for the report - they indeed weren't exported in the package.json `files`. PR #400 has been opened to fix.
