### ISSUE TITLE
[number field] Implement `inputmode` for mobile keyboard support

### ISSUE THREAD

**Issue by mj12albert** [mui/base-ui#40]
Raised in https://github.com/mui/material-ui/pull/36119#issuecomment-1678269343

The `inputmode` attribute hints to browsers for devices with software keyboards to determine which keyboard to provide when an input is focused. It should be returned by `getInputProps()`.

#### References

- https://css-tricks.com/everything-you-ever-wanted-to-know-about-inputmode/
- https://react-spectrum.adobe.com/blog/how-we-internationalized-our-numberfield.html#mobile

**Comment by mj12albert** [comment]
Manually test/benchmark first, we need to make sure the `-` and `.` characters are available

**Comment by michaldudak** [comment]
This is supported by the new NumberField component.
