### ISSUE TITLE
[Menu] Closing the menu with Tab doesn't restore focus to the trigger element

### ISSUE THREAD

**Issue by m4theushw** [mui/base-ui#411]
### Steps to reproduce

Link to live example: https://codesandbox.io/p/sandbox/unruffled-mirzakhani-8zvqrp?file=%2Fsrc%2FDemo.tsx

[menu.webm](https://github.com/mui/material-ui/assets/42154031/60f66d0e-65c6-4acf-9599-db9eb31c45ee)

### Current behavior

Pressing <kbd>Tab</kbd> closes the menu and, since it's portaled and there's no other element after it, the focus goes to `<body>`.

### Expected behavior

The focus should return to the element that triggered the menu, like how <kbd>Esc</kbd> works.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: base menu tab

**Search keywords**:

**Comment by michaldudak** [comment]
Thanks for the report. We're starting to overhaul the Base UI's Menu and will consider fixing this bug in the new version.
