### ISSUE TITLE
[TextareaAutosize] Disappearing text in microsoft edge browser

### ISSUE THREAD

**Issue by UnpaidIntern1** [mui/base-ui#452]
### Steps to reproduce

Link to live example: https://codesandbox.io/p/sandbox/xenodochial-bassi-zx55lx?file=%2Fsrc%2FDemo.tsx

i am using the codesandbox from the mui base demo for textareaautosize

Steps:
1. Make sure you open this in Microsoft Edge
2. Type in "I am testing this right now right now"

### Current behavior

The second "now" becomes invisible once you start typing it and reappears when you finish typing. 

https://github.com/mui/base-ui/assets/171741092/fceeecae-fbcd-4634-804a-c8ee91db0b9f

### Expected behavior

Text should not disappear.

short video of testing this in google chrome browser

https://github.com/mui/base-ui/assets/171741092/109c17c1-cab3-4370-bd95-f0ff1b71ef1c

### Context

Wondering why the text disappears only in microsoft edge. I tested this in incognito mode for microsoft edge and the text does not disappear which is weird.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Disappearing text, microsoft edge

**Comment by UnpaidIntern1** [comment]
@mj12albert Is there any update on this?

**Comment by mj12albert** [comment]
@UnpaidIntern1 I can reproduce this, though it's an issue with Edge and not the component

It will work as expected if you turn off Edge's text prediction feature:

![Screenshot 2024-06-18 at 8 34 10 PM](https://github.com/mui/base-ui/assets/4997971/117d1c45-c863-47a3-a835-ef3f60882516)
