### ISSUE TITLE
[Menu] Configure MenuItems not to close the Menu when clicked

### ISSUE THREAD

**Issue by michaldudak** [mui/base-ui#46]
https://github.com/mui/material-ui/issues/38324#issuecomment-1682293358

Consider adding a prop (such as `disableCloseOnClick`) that modifies the default MenuItem behavior.

**Comment by mainakkaniam** [comment]
I would like to look into this matter. From what you said what I understood is that you meant this behaviour: in the official MUI menu docs , there is a "Dashboard" example , on clicking menu appears and on clicking any of the menuitem it disappears. You want to give an option to the developer to keep the menu alive even when the user clicks on any of menuitem. 
Please  confirm and would love to have some help regarding how to approach the problem.

**Comment by michaldudak** [comment]
That's correct. This can be implemented in the `useMenuItem` hook (`createHandleClick` function). Add the `disableClosingOnClick` parameter to the hook, check its value in the click handler, and call `dispatch({ type: DropdownActionTypes.close })` only when it's false.
Please also add a test verifying this behavior.

**Comment by Jaswanth-Sriram-Veturi** [comment]
Can I work on this issue?

**Comment by michaldudak** [comment]
Go ahead!
