### ISSUE TITLE
Remove workarounds for unsupported browsers

### ISSUE THREAD

**Issue by michaldudak** [mui/base-ui#47]
Some Base UI components use workarounds for issues found in older browsers (IE, Safari < 13). We can remove them to reduce the bundle size:

- [ ] touch action support detection in useSlider: https://github.com/mui/material-ui/blob/846bc16fb3f02e9b64573a4aaaa0bd5aea2be36f/packages/mui-base/src/useSlider/useSlider.ts#L174-L194
- [ ] non-standard key codes in useSnackbar (`Esc`): https://github.com/mui/material-ui/blob/846bc16fb3f02e9b64573a4aaaa0bd5aea2be36f/packages/mui-base/src/useSnackbar/useSnackbar.ts#L43-L44
- [ ] IE-specific support in FocusTrap: https://github.com/mui/material-ui/blob/846bc16fb3f02e9b64573a4aaaa0bd5aea2be36f/packages/mui-base/src/FocusTrap/FocusTrap.tsx#L198-L205
- [ ] Handling focus on disabled elements in useInput: https://github.com/mui/material-ui/blob/846bc16fb3f02e9b64573a4aaaa0bd5aea2be36f/packages/mui-base/src/useInput/useInput.ts#L109-L114

Note that Material UI components that use these Base UI building blocks should still support these older browsers (until the next major version).

Part of mui/material-ui#34510

**Comment by omriklein** [comment]
Hey, is this free to take?
I'll  be happy to work on this

**Comment by mapache-salvaje** [comment]
Go for it @omriklein !

**Comment by axelbostrom** [comment]
Hi. is anyone still working on this? Otherwise I would gladly have a look at this. If possible, just to clarify, I should not remove the old browser support for the Material UI components that use these Base UI building blocks. So just make sure which they are and leave them?

**Comment by michaldudak** [comment]
@omriklein, are you still working on this?

@axelbostrom, in cases where a Material UI component uses a Base UI component, the idea is to move the polyfills and workarounds from Base UI to Material UI (as we can't reduce Material UI's support between majors). However, in cases where this would require hacks or impact performance, we could leave it as is and come back to this issue when we release the next major.

**Comment by omriklein** [comment]
@michaldudak hey, sorry. I didn't have time for it. You're welcome to do it if you want.

**Comment by ekailly** [comment]
Hi, is anyone still working on this?

If not, I'd like to pick this up 🙂

**Comment by michaldudak** [comment]
Go ahead, @ekailly!
