### ISSUE TITLE
[Select] On Safari, clicking on the Select input does not close its listbox

### ISSUE THREAD

**Issue by nangelina** [mui/base-ui#476]
### Steps to reproduce

Link to live example: https://mui.com/base-ui/react-select/#introduction

Steps:
1. Use Safari (I am on Version 17.5)
1. Click the input once to open the listbox
2. Click the input again to try to close it

### Current behavior

On Safari, clicking the input closes and reopens the listbox.

https://github.com/user-attachments/assets/54357ef1-6fa0-4d81-a7ca-fba7c72f864b

### Expected behavior

On Chrome, clicking the input closes the listbox.

https://github.com/user-attachments/assets/69b8e4c1-6ec9-4e56-82df-067580747172

### Your environment

Safari Version 17.5 (19618.2.12.11.6)

**Search keywords**: select, listbox, menu, safari, close

**Comment by michaldudak** [comment]
We are going to revamp the Select (see https://github.com/mui/base-ui/issues/217) soon, and we'll make sure this issue is resolved in the new version.
