### ISSUE TITLE
[Slider] `track="inverted"` does not work

### ISSUE THREAD

**Issue by Fireclunge** [mui/base-ui#48]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:
https://codesandbox.io/s/practical-knuth-qgjfw9?file=/Demo.js

Steps:

1. add track="inverted" to <StyledSlidebar/>

### Current behavior 😯

track="inverted" does nothing. It is the same behavior as the default "normal"

### Expected behavior 🤔

The slidebar track should come in from the right as opposed to the left

### Context 🔦

I'm trying to get the track to come in from the right

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by mj12albert** [comment]
In the new API, the current Track component that represents the "fill bar" of the slider will be deprecated. The name "Track" (`<Slider.Track />`) will be used to refer to the full width of the slider, or the full "touchable" area to be more precise.

The `marks` prop and `Mark`/`MarkLabel` components will also be dropped.

For now, the new API will provide a `useSliderContext` hook that can be used to implement these (sub)components, here are some demos from https://github.com/mui/base-ui/pull/373
- inverted fill: https://deploy-preview-373--base-ui.netlify.app/experiments/slider-inverted-fill/
- marks, fill, inverted fill: https://deploy-preview-373--base-ui.netlify.app/experiments/slider-marks/

**Comment by mj12albert** [comment]
**UPDATE:** Hooks and contexts will not be in the public API (at least for now)

>Expected behavior
>The slidebar track should come in from the right as opposed to the left

To achieve this, either make the slider RTL, or style the track and indicator to make it appear ["inverted"](https://master--material-ui.netlify.app/material-ui/react-slider/#inverted-track)
