### ISSUE TITLE
[core] Confusing source folder name

### ISSUE THREAD

**Issue by oliviertassinari** [mui/base-ui#482]
### Steps to reproduce

The sources are located at https://github.com/mui/base-ui/tree/master/packages/mui-base/ but the npm package name is `@base_ui/react`. So I would expect the source to be located at https://github.com/mui/base-ui/tree/master/packages/base-ui-react/.

**Comment by michaldudak** [comment]
That's the plan. However, there's some shared infra code assuming `mui-*` format, so it has to be made configurable. Shipping components felt like a more important thing to do, so I deprioritized this issue, but it's still on the radar.

**Comment by oliviertassinari** [comment]
@michaldudak Yeah, not a priority.

I wanted to have it in the backlog, it could be for a community contribution or down the line, for a day where we want someone a bit more brainless to relax 😁
