### ISSUE TITLE
[Menu] Create the checkbox menu item

### ISSUE THREAD

**Issue by michaldudak** [mui/base-ui#52]
Create a component that acts as a selectable menu item. It should follow the spec for the ARIA `menuitemcheckbox` role (https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/menuitemcheckbox_role).

**Comment by umrkhn** [comment]
Hi @michaldudak, I would like to work on this issue.

**Comment by michaldudak** [comment]
We need to create the `useCheckbox` hook first (#38036), as the checkbox item will likely require it.
Creating new components is currently not high on our priority list (we're focusing on stabilizing the library to release the stable version), so I won't be able to spend much time defining the specs for it.

**Comment by umrkhn** [comment]
@michaldudak let me know if there's something i can contribute to the project.

**Comment by michaldudak** [comment]
We don't have community-friendly issues in Base UI at the moment. For other projects, you can browse the "ready to take" issues: https://github.com/mui/material-ui/labels/ready%20to%20take
