### ISSUE TITLE
[Menu] Create the radio menu item

### ISSUE THREAD

**Issue by michaldudak** [mui/base-ui#53]
Create a component that acts as a selectable menu item. It should follow the spec for the ARIA `menuitemradio` role (https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/menuitemradio_role).

**Comment by r055a** [comment]
Hi @michaldudak can I please be assigned to this Issue

**Comment by michaldudak** [comment]
This is not up for grabs yet. We don't have the details fleshed out. We likely need to create the radio button (#38038) first.
