### ISSUE TITLE
[docs] Restore documentation for states CSS customizations

### ISSUE THREAD

**Issue by oliviertassinari** [mui/base-ui#543]
### Steps to reproduce

1. Open https://master--base-ui.netlify.app/base-ui/react-switch/

### Current behavior

No documentation on the different DOM states that can be customized, e.g. `[data-disabled]`

### Expected behavior

Clear API documentation on the CSS API that is available to customize the component. https://mui.com/base-ui/react-switch/components-api/#switch-classes

### Context

This is a regression from the DX with @mui/base / @mui/material. Those new states are not automatically documented anymore.

I saw this raised in https://mui-org.slack.com/archives/C05SBSU8NPR/p1723629104973729?thread_ts=1723628372.562069&cid=C05SBSU8NPR.

---

As a side note, there are also considerations to have with the performance of this new approach: https://mui-org.slack.com/archives/C05SBSU8NPR/p1723640921594739?thread_ts=1723628372.562069&cid=C05SBSU8NPR

<img width="471" alt="SCR-20240817-qjxk" src="https://github.com/user-attachments/assets/aeede025-ef15-49f5-b09e-6533ba304124">

https://www.youtube.com/watch?v=nWcexTnvIKI 

### Benchmarks

- https://qwikui.com/docs/headless/select/

<img width="539" alt="SCR-20240819-rqrs" src="https://github.com/user-attachments/assets/e33dfd97-1e18-4646-a713-671e8536974c">

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: -

**Comment by michaldudak** [comment]
We're aware the documentation is lacking in this regard. We're going to update it before the stable release.

**Comment by oliviertassinari** [comment]
@michaldudak cool, no urgency on fixing this, but I wanted to flag the need to design this in a way that we can eventually automatically document. If we can't, then I think to design differently.

**Comment by michaldudak** [comment]
This will be closed once the changes introduced in https://github.com/mui/base-ui/pull/818 are propagated to all the pages.

**Comment by mj12albert** [comment]
Completed in https://github.com/mui/base-ui/pull/818
