### ISSUE TITLE
[Select] Highlight doesn't highlight properly if an Option has the value null

### ISSUE THREAD

**Issue by adamhylander** [mui/base-ui#56]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/keen-david-z2r399?file=/src/Demo.tsx

The reproduction is taken from the [docs](https://mui.com/base-ui/react-select/).

Steps:

1. Open the first select
2. Press down-arrow key multiple times
3. Press up-arrow key multiple times

### Current behavior 😯

Pressing the down-arrow key doesn't highlight anything but pressing the up-arrow key highlights normally excluding the null value. For the second select, pressing the down-arrow key only highlights the first option and the up-key can only highlight the bottom two options. 

### Expected behavior 🤔

Pressing either direction key should skip null value Options and highlight the first possible non-null value

### Context 🔦

Found while testing

### Your environment 🌎

<details>
This was done using Firefox Browser. For environment see linked codesandbox.io
</details>

**Comment by ZeeshanTamboli** [comment]
Seems like a bug. Also, the prop types warning for a `null` value shouldn't appear if we are supposed to support null as an option value. I also noticed it's broken in this demo: https://mui.com/base-ui/react-select/#selected-value-appearance.
