### ISSUE TITLE
[useScrollLock] overflow-y: scroll support no longer working

### ISSUE THREAD

**Issue by oliviertassinari** [mui/base-ui#611]
### Steps to reproduce

Steps:
1. Go to https://master--base-ui.netlify.app/components/react-dialog/

https://github.com/user-attachments/assets/053553bc-4ca5-4fff-afcf-bac267437d67

### Current behavior

Doesn't restore the value, it's overridden, so it introduces a layout shift.

### Expected behavior

Correctly restore the previous values. For example https://github.com/mui/material-ui/blob/012c2e899b9a8977bb326746f43ef19a5f4f01a7/packages/mui-material/src/Modal/ModalManager.ts#L143 from https://mui.com/base-ui/react-modal/, it works.

### Context

The support for `overflow-y: scroll` is needed to solve bugs like https://github.com/mui/material-ui/pull/40749, until we can rely on #79.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: -

**Comment by vladmoroz** [comment]
Fixed in #604
