### ISSUE TITLE
[docs-infra] Crash build when description is over 170 characters

### ISSUE THREAD

**Issue by oliviertassinari** [mui/base-ui#612]
### Steps to reproduce

https://app.ahrefs.com/site-audit/6984453/data-explorer?columns=pageRating%2Curl%2Ctraffic%2ChttpCode%2Cdepth%2CmetaDescription%2CmetaDescriptionLength%2CnrMetaDescription%2Ccompliant&current=14-09-2024T115402&filterId=2864d4a78dbccdda9cf9629aa273bd61&issueId=c64d56c9-d0f4-11e7-8ed1-001e67ed4656 shouldn't be possible to happen in the first place.

<img width="1119" alt="SCR-20240914-pdyc" src="https://github.com/user-attachments/assets/9c1b5b2a-266c-4f2e-a6d7-2939008207e0">

### Current behavior

Build pass

### Expected behavior

Build crash

<img width="944" alt="SCR-20240914-pdav" src="https://github.com/user-attachments/assets/97711b15-ca25-478b-9bec-31f925aecb77">

I think we should bring this back from https://github.com/mui/material-ui/blob/64741295f7c233bd1782086e0187e52b668cb78c/packages/markdown/prepareMarkdown.js#L94. It would be a regression otherwise once Material UI eventually relies on the new docs-infra we are working on here. It's a regression compared to https://mui.com/base-ui/getting-started/ docs-infra.

### Motivation

See https://github.com/mui/material-ui/pull/43562 for why it matters. It's about having a description that fits into the Google Search results.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: -

**Comment by michaldudak** [comment]
Fixed in #892
