### ISSUE TITLE
[Dialog] Clicking the trigger doesn't close non-modal dialogs

### ISSUE THREAD

**Issue by vladmoroz** [mui/base-ui#619]
### Steps to reproduce

Link to live example:
https://codesandbox.io/p/sandbox/2ny6h6?file=%2Fsrc%2FApp.tsx%3A8%2C46

Click the trigger multiple times.

### Current behavior

When dialog is open, dialog popup re-opens when clicking the trigger

### Expected behavior

When dialog is open, dialog popup should close when clicking the trigger

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: dialog, non-modal, trigger, close

**Comment by onehanddev** [comment]
Hi @vladmoroz👋 
 If this is still open for pick up, I’d like to work on this issue. Could you please assign it to me? Thanks!

**Comment by michaldudak** [comment]
Hi! We need to change the implementation of the Dialog slightly so a couple of other issues will be solved as well. Thanks for your willingness to help, but we'll handle this one within the team.
