### ISSUE TITLE
[Autocomplete] useAutocomplete - Autocomplete input does not show selected values in multiple mode;`inputValue` is empty when Autocomplete is in multiple mode.

### ISSUE THREAD

**Issue by 340rahul** [mui/base-ui#634]
### Steps to reproduce

Link to live example: [(required)](https://codesandbox.io/p/devbox/qg7knz?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm17t1boe00073b6ieydak6tu%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm17t1bod00023b6i1vat80p8%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm17t1boe00043b6i584ak67d%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm17t1boe00063b6idna6jv16%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm17t1bod00023b6i1vat80p8%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm17t1boc00013b6iou9y366h%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522cm17t1bod00023b6i1vat80p8%2522%252C%2522activeTabId%2522%253A%2522cm17t1boc00013b6iou9y366h%2522%257D%252C%2522cm17t1boe00063b6idna6jv16%2522%253A%257B%2522id%2522%253A%2522cm17t1boe00063b6idna6jv16%2522%252C%2522activeTabId%2522%253A%2522cm17tbcvz007h3b6ijykft36y%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm17t1boe00053b6ix46569yy%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522cm17tbcvz007h3b6ijykft36y%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522cm17t1boe00043b6i584ak67d%2522%253A%257B%2522id%2522%253A%2522cm17t1boe00043b6i584ak67d%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm17t1boe00033b6in8x5fpse%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cm17t1boe00033b6in8x5fpse%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Steps:
1. Create a multi-select Autocomplete component using the `useAutocomplete` hook from `base-ui`
2. Selected options do not render in the input field when using the component above

Demo can be seen in the linked codesandbox above

### Current behavior

In an Autocomplete created with `useAutocomplete` hook with multiple mode enabled, the selected options are not rendered in the input field.

### Expected behavior

The selected options should be rendered in the input field of the autocomplete.

### Context

From what I can tell, this is probably because in `resetInputValue` function within `useAutocomplete.js`, the inputValue is set to "" when `multiple` is `true`.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 14.5
  Binaries:
    Node: 22.5.1 - ~/.nvm/versions/node/v22.5.1/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v22.5.1/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 128.0.6613.138
    Edge: Not Found
    Safari: 17.5
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.1 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.27 
    @mui/core-downloads-tracker:  5.15.0 
    @mui/icons-material: ^5.14.14 => 5.14.14 
    @mui/material: ^5.15.0 => 5.15.0 
    @mui/private-theming:  5.15.0 
    @mui/styled-engine:  5.15.0 
    @mui/system:  5.15.0 
    @mui/types:  7.2.11 
    @mui/utils:  5.15.0 
    @mui/x-data-grid:  6.15.0 
    @mui/x-data-grid-premium: ^6.15.0 => 6.15.0 
    @mui/x-data-grid-pro:  6.15.0 
    @mui/x-date-pickers:  6.15.0 
    @mui/x-date-pickers-pro: ^6.15.0 => 6.15.0 
    @mui/x-license-pro:  6.10.2 
    @types/react: 18.2.44 => 18.2.44 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: 5.2.2 => 5.2.2 
```
</details>

**Search keywords**: useAutocomplete Autocomplete inputValue

**Comment by michaldudak** [comment]
When in multiple mode, the Autocomplete does not display its value in the input, but instead lets you render selected values as pills (or whatever you like, really). You can access the values with the `value` parameter returned from `useAutocomplete`. See https://mui.com/material-ui/react-autocomplete/#customized-hook for an example.
