### ISSUE TITLE
[Select] Mouse pointer doesn't steal focus on hover 

### ISSUE THREAD

**Issue by michaldudak** [mui/base-ui#64]
Mousing over an Option should steal focus. Currently, mousing over Options doesn’t move focus to that Option.

https://github.com/mui/material-ui/assets/4696105/a650edd9-8c1e-4fbf-a760-701c11bccd36

Compare it to the Menu which highlights items on hover (merged to master but not released yet in Base UI as of Jan 30):

https://github.com/mui/material-ui/assets/4696105/9392bb0b-73a3-4a57-b71a-45df2238f900

The implementation should be similar to the changes in Menu done in mui/material-ui#40755

**Search keywords**:

**Comment by AbhiGhoghari** [comment]
Could you provide a screenshot or video?

**Comment by michaldudak** [comment]
@AbhiGhoghari I updated the description.
