### ISSUE TITLE
[Select] Typeahead doesn't work on a closed Select

### ISSUE THREAD

**Issue by michaldudak** [mui/base-ui#65]
When a Select is closed but focused, pressing a character key should open it and move focus to the first option matching the pressed key. Currently, pressing character keys on a closed Select has no effect.

**Search keywords**:

**Comment by ZeeshanTamboli** [comment]
@michaldudak, this issue (https://github.com/mui/material-ui/issues/42539) seems related. But instead it describes cycling through options in a closed state when a character key is pressed, similar to the behavior in the native Select (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select).

Modified code:
```html
<label for="pet-select">Choose a pet:</label>
<select name="pets" id="pet-select">
  <option value="">--Please choose an option--</option>
  <option value="dog 1">Dog 1</option>
  <option value="dog 2">Dog 2</option>
  <option value="hamster">Hamster</option>
  <option value="parrot">Parrot</option>
  <option value="spider">Spider</option>
  <option value="goldfish">Goldfish</option>
</select>
```
Can you take a look at https://github.com/mui/material-ui/issues/42539?

**Comment by michaldudak** [comment]
Thanks for letting me know!
@colmtuite, FYI, we can consider it when designing the overhauled Select.
