### ISSUE TITLE
Clean up exports

### ISSUE THREAD

**Issue by vladmoroz** [mui/base-ui#650]
The DX of importing Base UI components should be cleaned up to avoid unnecessary noise:
- Each component should be exported once, and not its parts
- Types should be namespaces under component name
- Hooks should not be exported

For example, typing `Dialog` in VSC should _not_ suggest anything but the `Dialog` component.

Expected import styles:
```jsx
import { Dialog } from '@base_ui/react';
import * as Dialog from '@base_ui/react/Dialog';
```

Shouldn't be a thing:
```tsx
import { DialogRoot } from '@base_ui/react';
import type { DialogRootProps } from '@base_ui/react/Dialog/...'
```

**Comment by michaldudak** [comment]
Based on our discussions, we agreed to drop the `import * as Foo` pattern and replace it with `import { Foo }`, so it's easier to type and VSCode suggestions include it.

```tsx
import { Dialog } from '@base_ui/react';
import { Dialog } from '@base_ui/react/Dialog';
```
