### ISSUE TITLE
Remove `animated` prop in favour of a provider component

### ISSUE THREAD

**Issue by vladmoroz** [mui/base-ui#655]
`animated` prop is primarily needed to make tests run faster and easier to write

We need to remove it from the components and expose a provider to set the value globally

**Search keywords**:

**Comment by mj12albert** [comment]
Just to confirm, with this change if you wanted to disable animations for one component, you cannot simply do:
```jsx
<Tooltip.Root animated={false}>
```
and must instead do this?
```jsx
<AnimationProvider disabled>
  <Tooltip.Root>
</AnimationProvider>
```

API wise, `<AnimationProvider disabled>` seems obvious enough? `<AnimationProvider animated={disabled}>` doesn't seem much better considering it's more verbose

**Comment by vladmoroz** [comment]
> Just to confirm, with this change if you wanted to disable animations for one component, you cannot simply do:

Yeah we have discussed that disabling animations granularly is not really a use case, and when running tests, you'd disable them on the whole thing

> API wise, <AnimationProvider disabled> seems obvious enough? <AnimationProvider animated={disabled}> doesn't seem much better considering it's more verbose

We haven't discussed the exact API yet, but yeah, something like `<AnimationProvider disabled>` sounds right. Maybe even something like `<NoAnimations>` or `<SkipAnimations>` since there no reason to import it other than disable the animations
