### ISSUE TITLE
[TextareaAutosize] Incorrect height calculation when `box-sizing: border-box`

### ISSUE THREAD

**Issue by michaldudak** [mui/base-ui#68]
The component seems to ignore `box-sizing: border-box` with respect to padding, when calculating the computed height. When I apply vertical padding and a height of 32px, I can’t seem to center the text in the textarea. But I can achieve this with a native textarea using the same styles.

**Search keywords**:

**Comment by ANUGLYPLUGIN** [comment]
Can I take these? It looks same as docs problem which I mentioned https://github.com/mui/material-ui/issues/40634

**Comment by michaldudak** [comment]
Sure, go ahead!

**Comment by ANUGLYPLUGIN** [comment]
@michaldudak I am sorry that I clicked randomly and remove this assignment.
I am confused with `pnpm test:coverage:ci` error in node `execFileSync` [pr link](https://github.com/mui/material-ui/pull/40646)
It will report error in main branch as well.

**Comment by colmtuite** [comment]
Auto-sizing can be handled natively these days with `field-sizing`. So we're going to deprecate this component soon.

[Demo](https://jsfiddle.net/as0r6evg/)
