### ISSUE TITLE
[Popup] Expose the arrow slot

### ISSUE THREAD

**Issue by michaldudak** [mui/base-ui#69]
There are use cases that require the arrow pointing from the popup toward the triggering element to be present and stylable. See https://floating-ui.com/docs/arrow

**Search keywords**:

**Comment by michaldudak** [comment]
The new Popover (and other similar components) support the Arrow subcomponent.

**Comment by noranda** [comment]
> The new Popover (and other similar components) support the Arrow subcomponent.

@michaldudak Is this an MUI base component? I don't see any support in either `Popup` or `Popper`.

**Comment by michaldudak** [comment]
This was done in @base_ui/react, not in @mui/base. I realize the current situation may be somewhat confusing, but we hope to make it clearer soon, with the launch of new docs.
