### ISSUE TITLE
[docs] API table issues

### ISSUE THREAD

**Issue by mnajdova** [mui/base-ui#696]
### Steps to reproduce

Link to live example: https://deploy-preview-541--base-ui.netlify.app/components/react-select/

### Current behavior

1. For the properties that are enum or union, there is no information on the available values, e.g.:

```
alignMethod | enum | 'item' | Determines if the select should align to the selected item inside the popup or the trigger element.
```

2. There is overlap in the UI for the properties with longer names:

<img width="667" alt="Screenshot 2024-10-01 at 11 41 13" src="https://github.com/user-attachments/assets/8baedfcd-1e08-4f7c-971f-b323cc8689f3">

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: docs, API table

**Comment by michaldudak** [comment]
These are two separate issues. I can take a look at 1. and @vladmoroz should consider 2. when redesigning the docs.

**Comment by vladmoroz** [comment]
Yep this is on my radar
