### ISSUE TITLE
[accordion] Support "hidden=until-found" pattern

### ISSUE THREAD

**Issue by oliviertassinari** [mui/base-ui#702]
### Summary

The `hidden="until-found"` attribute isn't widely available yet: https://caniuse.com/mdn-html_global_attributes_hidden_until-found_value but it would be great to plan its support. It's better UX. https://developer.chrome.com/docs/css-ui/hidden-until-found for more details

We also have something related to not mounting children to save performance https://mui.com/material-ui/react-accordion/#performance, and this would be another part of the tradeoff for developers when deciding which path they take.

### Examples

- React Aria added support in https://github.com/adobe/react-spectrum/pull/6931. 

**Search keywords**: -

**Comment by colmtuite** [comment]
@oliviertassinari It's already supported in our Accordion component.

**Comment by oliviertassinari** [comment]
@colmtuite I have linked this issue with its PR 4 minutes before you commented 👍.

I noticed this issue while I was browsing with Jose the tiptap pricing page and got frustrated I couldn't search in their FAQ accordion https://tiptap.dev/pricing.

**Comment by oliviertassinari** [comment]
And to wrap this up, to turn every stone 🗿: 

- Step 1. Reference https://github.com/radix-ui/primitives/issues/1660 so that developers landing on that issue can find a backlink back to here. Could help a bit with the Base UI go-to-market.

<img width="792" alt="SCR-20241215-uhbd" src="https://github.com/user-attachments/assets/ac1b2a6f-9432-44e5-844d-5dc302d1dbb7" />

- Step 2. Share the progress on Twitter, it's a step forward: https://x.com/olivtassinari/status/1868422851122053377 (a subtle pun on the Vercel pricing page 😁, and reinforce that it's open-source, in case)
