### ISSUE TITLE
Implement `initialFocus` and `finalFocus` props across relevant components

### ISSUE THREAD

**Issue by colmtuite** [mui/base-ui#714]
You should be able to pass a `ref` or function. We decided not to implement the `content|auto` string values. This prop should be ignored on touch devices, where focus should always go to the Popup element.

**Search keywords**:

**Comment by michaldudak** [comment]
To be clear: this applies to Dialog, AlertDialog, and Popover, right?

**Comment by colmtuite** [comment]
> this applies to Dialog, AlertDialog, and Popover, right?

Correct
