### ISSUE TITLE
Add `[data-pressed]` attr to Menu + Popover triggers

### ISSUE THREAD

**Issue by colmtuite** [mui/base-ui#716]
To avoid style conflicts with data attrs—particularly with Tooltip—we decided to add a `[data-pressed]` attribute to Menu + Popover trigger components when they’re opened via click. We will keep the `[data-open]` attribute alongside this.

**Search keywords**:

**Comment by onehanddev** [comment]
Hello! @colmtuite 👋 
Is this issue still available to work on? If so, I’d love to take it up and start working on it. Please let me know if there are any specific guidelines or prerequisites I should be aware of before getting started.
