### ISSUE TITLE
[number field] Pressing and holding the stepper buttons should continuously change the value until released

### ISSUE THREAD

**Issue by mj12albert** [mui/base-ui#74]
Pressing and holding down the increment or decrement should continuously change the value until the button is released. Both clicks and keypresses should be able to trigger this behavior.

#### References
- Mantine: https://mantine.dev/core/number-input/#incrementdecrement-on-hold https://github.com/mantinedev/mantine/issues/525
- `<input type="number">`: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number

**Search keywords**:

**Comment by michaldudak** [comment]
This has been implemented in the NumberField component.
