### ISSUE TITLE
[Tabs] Widen value type to any

### ISSUE THREAD

**Issue by oliviertassinari** [mui/base-ui#81]
### Summary

The `value` prop can be string or number https://mui.com/base-ui/react-tabs/components-api/#tab-prop-value but why not `any`? There don't seem to be limiting factors for this.

So I think we should widen the type on all tabs components, Base UI, Material UI, Joy UI to `any` when possible.

### Motivation

https://github.com/mui/material-ui/issues/40630

**Search keywords**: value type any

**Comment by flaviendelangle** [comment]
We already have an issue that seems very similar mui/material-ui#40801

**Comment by DiegoAndai** [comment]
Should we use `unknown` instead of `any` for this? see https://github.com/mui/material-ui/issues/16065#issuecomment-499263327 and https://github.com/mui/material-ui/issues/16065#issuecomment-499461689

**Comment by michaldudak** [comment]
Good point. It will make it less convenient to use controlled Tabs, though (onValueChange argument will always have to be casted). If we made Tabs.Root generic over `value`, the experience would be better, but the type of the value wouldn't be propagated to Root's subcomponents:
```
const [val, setVal] = React.useState<number | null>(0);

return (
  <Tabs.Root value={val} onValueChange(newVal => setVal<newVal>)
  //                 ↑                   ↑ 
  //                 │                   └─ same type as `val`
  //                 └─ inferred as `number | null`
    <Tabs.Panel value={1}
    //                 ↑ 
    //                 └─ unknown

**Comment by DiegoAndai** [comment]
> If we made Tabs.Root generic over value, the experience would be better, but the type of the value wouldn't be propagated to Root's subcomponents

Propagating the type to subcomponents is not supported in Typescript, right? So that's a Typescript limitation.

If we set it as `unknown`, users would have to do this, right?:

```jsx
const [val, setVal] = React.useState<number | null>(0);

return (
  <Tabs.Root value={val} onValueChange(newVal => setVal<newVal>)
    <Tabs.Panel<number> value={1}
```

That's more cumbersome, but it's the only way we can provide real type safety, isn't it? `any` is just turning off type safety.
