### ISSUE TITLE
[AlertDialog] Implement AlertDialog

### ISSUE THREAD

**Issue by danilo-leal** [mui/base-ui#83]
API TBD.[ARIA Pattern](https://www.w3.org/WAI/ARIA/apg/patterns/alertdialog).

**Comment by colmtuite** [comment]
Closing this since we decided to handle it in Dialog.

**Comment by benface** [comment]
@colmtuite – I was going to create an issue to clarify the difference between `Dialog` and `AlertDialog` and I stumbled upon this. Is the decision to "handle [alertdialog] in Dialog" still valid, and if so, does it mean we shouldn't be using the `AlertDialog` component?

**Comment by colmtuite** [comment]
@benface I don't remember what that's about. We currently have no plans to deprecate AlertDialog or to support its behaviour on Dialog.

**Comment by benface** [comment]
Thanks for the answer @colmtuite, I created a new issue here: #1687
