### ISSUE TITLE
[docs] `theme.css` in CSS Modules demos are linked incorrectly in CSB

### ISSUE THREAD

**Issue by mj12albert** [mui/base-ui#894]
Example: https://master--base-ui.netlify.app/components/react-collapsible

For the first demo, choose `CSS Modules` and click the `CodeSandbox` button. The `theme.css` file is generated correctly, but not linked in `index.html`:

![Screenshot 2024-11-29 at 2 15 50 PM](https://github.com/user-attachments/assets/7335ccf8-bb6a-463e-93d9-606817f87dcb)

**Search keywords**:

**Comment by mj12albert** [comment]
@vladmoroz Is this an issue? The sandboxes generated off the `/new` docs route seem fine

**Comment by vladmoroz** [comment]
If `/new` works then it's fine (not sure why it'd work, but whatever) 
We'll move over all from `/new` to root before the release
