### ISSUE TITLE
[Positioner] Support logical `side` prop

### ISSUE THREAD

**Issue by mj12albert** [mui/base-ui#951]
Currently to position an RTL menu this is needed:
```jsx
<Menu.Positioner align="start" side={isRtl ? 'left' : 'right'}>
```
Which is a bit odd because `align` is already direction-aware

With a [`DirectionProvider`](https://github.com/mui/base-ui/issues/831) we can easily support (additional) logical `side`s as well that are direction aware using the [corresponding](https://css-tricks.com/css-logical-properties-and-values/#aa-positioning) CSS property names:
```
top: 'inset-inline-start'
right: 'inset-block-start'
bottom: 'inset-inline-end'
left: 'inset-block-end'
```

Applicable to all components with a `Positioner` and use `useAnchorPositioning`: Menu, Popover, PreviewCard, Select, Tooltip

**Search keywords**:

**Comment by mj12albert** [comment]
@vladmoroz do you think its better to follow the CSS prop name completely or is `inset-` unnecessary?

**Comment by vladmoroz** [comment]
I think it totally has to be without `inset-`, it actually makes it more confusing. Those CSS properties themselves left/right/etc. are unrelated.
