### ISSUE TITLE
[Popover] Touch interactions

### ISSUE THREAD

**Issue by vladmoroz** [mui/base-ui#954]
- Sometimes it's possible to open multiple popovers on a mobile device
- Tapping a button to open one popover and then tapping quickly another one while the first one is still animating in won't open the last one like on desktop. Instead, the first one flickers and re-opens.

https://github.com/user-attachments/assets/d77b4d27-75d4-4344-9520-998fd240b302

**Search keywords**:

**Comment by atomiks** [comment]
First dot point will be fixed with https://github.com/floating-ui/floating-ui/pull/3130

**Comment by atomiks** [comment]
> Tapping a button to open one popover and then tapping quickly another one while the first one is still animating in won't open the last one like on desktop. Instead, the first one flickers and re-opens.

Haven't fully dug into this but wonder if it's related to small tap targets (<40px)? Seems like iOS decides to click the same button because it's too close perhaps? I'm not sure what would potentially cause the issue at the moment

**Comment by vladmoroz** [comment]
> Haven't fully dug into this but wonder if it's related to small tap targets (<40px)? Seems like iOS decides to click the same button because it's too close perhaps? I'm not sure what would potentially cause the issue at the moment

Yeah I can't reproduce it when tapping targets that are further away from each other. Probably you are right, might be an iOS thing
