### ISSUE TITLE
[popups] When opening on hover, wait for animations before impatient clicks

### ISSUE THREAD

**Issue by vladmoroz** [mui/base-ui#955]
For popups than open on hover, we've added a slight timeout that prevents impatient clicks from closing the popup immediately. It still feels like not enough if the popup is animating. Should the delay be contingent on the completion of animations/transitions? Possibly work like `Math.max(ourThreshold, animationDuration)`

**Search keywords**:

**Comment by atomiks** [comment]
> For popups than open on hover, we've added a slight timeout that prevents impatient clicks from closing the popup immediately.

We haven't though. Or maybe it just seems like that?

**Comment by vladmoroz** [comment]
> We haven't though. Or maybe it just seems like that?

Maybe I'm misremembering! No, I am bringing it up because impatient clicks just feel off and thought that we had something but it wasn't enough

**Comment by vladmoroz** [comment]
I think we definitely want to solve this before the alpha so that the docs feel sturdy.

**Comment by atomiks** [comment]
@vladmoroz I think reverting to the default "sticky" behavior seems better for now. 

It needs a solid implementation in Floating UI, such as the <100ms check, or something to do with animations, but it probably shouldn't be rushed. Although we might be able to do something externally, e.g. if they clicked before the animation finished or within 100ms, it should act like they didn't click at all? This way it neither closes nor sticks within the "impatient" threshold.
