### ISSUE TITLE
[Select] Retain the highlight state when closing

### ISSUE THREAD

**Issue by vladmoroz** [mui/base-ui#965]
This is mostly a nit/polish item.
When closing the select, there's a frame of slight flicker/unnecessary motion:

https://github.com/user-attachments/assets/0465c913-1dca-4a5f-bde0-f7db8eefbfce

Frame by frame:

1. Right after clicking an option: there's a highlight on the clicked option (possibly retained from the hover). The previous value still has the indicator.

<img src="https://github.com/user-attachments/assets/dc24b4ab-6bce-4bba-9e66-b5cd114d7b45" width="600" />

2. Next frame: the check icon is moved to its new place, but the highlight is lost

<img src="https://github.com/user-attachments/assets/b229c7f2-6a4b-4147-b435-568cca4bf1a1" width="600" />

3. The popup is closed

Ideally:
- If animated, I think we need to make sure that from frame (2), the highlight is set and persisted until mouse movement and/or popup is fully closed. When animating the popup, it should be animating with the newly highlighted item visible.
- If not animated, the Select should close immediately without frame (2)

**Search keywords**:

**Comment by atomiks** [comment]
> If not animated, the Select should close immediately without frame (2)

@michaldudak now I remember that's what the `flushSync` was for in Select - it skips that frame.  Removing it causes the 1 frame flash.

Retaining the highlight would fix that though even if the frame is kept.

I suppose this currently removes it?

```css
.Option[data-selected]:not([data-open]),
.Option[data-highlighted] {
  /* highlighted state */
}
```
