### ISSUE TITLE
[popups] Consistent popup focus and outline styles

### ISSUE THREAD

**Issue by vladmoroz** [mui/base-ui#975]
- Select Popup had an inline `outline: 0` which I removed because it was messing with my component styles as I was building out a demo for it
- Dialog and Popover popups may display an outline that's arguably never desirable
  - I'd never want to see a Dialog or Popover popup outline because those are not interactive and the only way it can end up there is programmatic focus, which feels disconnected from what I do as a user.
- Menu Positioner is focusable instead of its Popup part, displaying an unexpected outline
  <img src="https://github.com/user-attachments/assets/d871a544-fe9d-4d11-a6e2-d2f045e8d426" width="400" />

I'd suggest we set `outline: 0` via `:where(#popup-id)` on all non-interactive elements with tabindex so they don't need to be reset and don't override user styles as well; or at the very least consistently have or don't have the default focus outline on the Popup part.

Context:
https://github.com/mui/base-ui/pull/963#discussion_r1871124995

**Search keywords**:

**Comment by atomiks** [comment]
> Menu Positioner is focusable instead of its Popup part, displaying an unexpected outline

Positioners should be fully presentational, so we need to move the focus-related attributes and `getFloatingProps` calls to the `Popup`
