### ISSUE TITLE
[tabs] Fix `Tabs.Indicator` and `Tabs.Panel` export for API gen

### ISSUE THREAD

**Issue by vladmoroz** [mui/base-ui#995]
`Tabs.Indicator` produces `tabs-tab-indicator.json` instead of `tabs-indicator.json`

**Search keywords**:

**Comment by vladmoroz** [comment]
Panel also doesn't work
`Tabs.Panel` produces `tabs-tab-panel.json` instead of `tabs-panel.json`

**Comment by mnajdova** [comment]
Do you mean renaming:
- TabsTabInicator -> TabsIndicator
- TabsTabPanel -> TabsPanel
? I think the names came up from the fact that components were related to the Tab component, not the Tabs, but I can see the newly proposed names working as well. Let me tag @michaldudak as well to make sure this was the intention.

**Comment by michaldudak** [comment]
I chose these names purely for readability. `Tab` sounds better than `TabsTab`, for example. It's a pretty unique situation as we don't have the plural form as a component name elsewhere. I'm ok with renaming them to whatever works, as these names won't be used by developers anyway.

**Comment by vladmoroz** [comment]
@mnajdova whatever `TabsTabInicator` and `TabsTabPanel` is, it's not a part of the public API. The public API is `Tabs.Indicator` and `Tabs.Panel` and there seems to be some discrepancy between the internals and the public API, which results in this docs gen issue

**Comment by mnajdova** [comment]
Got ya, alright, it makes sense, I'll do the rename in https://github.com/mui/base-ui/pull/997
